# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  wiki:
    container_name: wiki-app
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/wiki
      - /wiki/node_modules
      - /wiki/.git
